Add user model
Iorhael/trainee-planner pull request #14
Opened 2023-08-14 15:40 UTC by Iorhael

2023-08-21 14:07 UTC, Iorhael commented on db/seeds.rb
> +end
Исправлено

2023-08-21 14:09 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +      t.string :last_name
Подумал, что и имя, и фамилия необязательны. 
![image](https://github.com/Iorhael/trainee-planner/assets/132287268/db7e347c-bd77-4af3-80d3-6d2948cd672a)
Окей, поправил.

2023-08-22 05:47 UTC, The7Fame commented on db/migrate/20230815123037_devise_create_users.rb
> +      t.string :last_name
Кстати, может, ты и прав. 
Я подумал, что когда пользователь log in, то он попадает на страницу приветствия, чтобы не было просто "Hello", поэтому и подумал, что firstname - обязательное поле.

2023-08-22 05:49 UTC, The7Fame approved these changes

2023-08-22 10:33 UTC, TsikhanauDzmitry requested changes

2023-08-22 10:33 UTC, TsikhanauDzmitry commented on Gemfile
> -  gem 'database_cleaner-redis'
Почему удалил этот гем?

2023-08-22 10:33 UTC, TsikhanauDzmitry commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:disable Metrics/MethodLength
Что это такое?

2023-08-22 10:33 UTC, TsikhanauDzmitry commented on db/migrate/20230815123037_devise_create_users.rb
> +      t.string :last_name
Почему обсуждение не зарезолвлено? @The7Fame

2023-08-22 10:33 UTC, TsikhanauDzmitry commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:enable Metrics/MethodLength
Это зачем?

2023-08-22 10:33 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +    email: "sample#{index}@sample.com",
Почему sample? Думаю, что лучшее решение: `user_#{i}@example.com`. Так мы будем точно знать, что это пользователь, а также по домену будет понятно, что это сделано сидами

2023-08-23 06:50 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:disable Metrics/MethodLength
Rubocop ругается на длину метода change в миграции. Подумал, что здесь ничего страшного не произойдёт если я отключу этого копа для данного метода. Из альтернатив можно разбить на несколько миграций, но мне показалось, что в данном случае будет удобнее читать, если всё будет в одной.

2023-08-23 06:52 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:enable Metrics/MethodLength
Rubocop просит re-enable своих копов после отключения.

2023-08-23 07:00 UTC, Iorhael commented on Gemfile
> -  gem 'database_cleaner-redis'
При ране rspec-а обнаружил, что стратегия `truncation` не существует для `redis`:
 `DatabaseCleaner::UnknownStrategySpecified: The 'truncation' strategy does not exist for the redis ORM!`

2023-08-23 07:01 UTC, Iorhael commented on db/seeds/development.rb
> +    email: "sample#{index}@sample.com",
Исправлено.

2023-08-23 11:37 UTC, The7Fame approved these changes

2023-08-24 09:03 UTC, The7Fame approved these changes

2023-08-24 10:21 UTC, TsikhanauDzmitry requested changes

2023-08-24 10:21 UTC, TsikhanauDzmitry commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:disable Metrics/MethodLength
Никаких комменатриев для рубокопа в коде не должно быть. Для этого существует yml файл

2023-08-24 10:21 UTC, TsikhanauDzmitry commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:enable Metrics/MethodLength
Этого не должно быть

2023-08-24 10:21 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Может быть лучше было бы вынесли фамилию в отдельный trait? Это же у нас не обязательное поле

2023-08-24 15:21 UTC, Iorhael commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Соглашусь. Готово.

2023-08-24 21:01 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:disable Metrics/MethodLength
Исправлено.

2023-08-24 21:01 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +  # rubocop:enable Metrics/MethodLength
Исправлено.

2023-08-25 05:36 UTC, The7Fame approved these changes

2023-08-25 09:40 UTC, TsikhanauDzmitry requested changes

2023-08-25 09:40 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    trait :default_last_name do
Трейты дополняют фактори. Потому лучше давать им более четкие имена. Чтобы потом они вызывались типа `create(:user, :with_last_name)`

2023-08-25 09:40 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
Добавь проверку на дефолтное значение имени, а также на трейт

2023-08-25 14:11 UTC, Iorhael commented on spec/factories/users.rb
> +    trait :default_last_name do
Готово.

2023-08-25 14:12 UTC, Iorhael commented on spec/models/user_spec.rb
Готово.

2023-08-27 12:15 UTC, The7Fame approved these changes

2023-08-28 13:17 UTC, Iorhael commented on db/migrate/20230815123037_devise_create_users.rb
> +      t.string :first_name,         null: false, default: ''
Дефолтное значение могло бы быть полезным, если бы мы применяли миграцию к уже существующей базе данных, где на поле first_name не стояло ограничения `null:false` и были значения `null`. В таком случае без дефолтного значения миграция бы завершилась с ошибкой. Но так как в нашем контексте не подрозумевается наличие уже сущестувующей таблицы `user`, то применение дефолтного значения действительно нецелесообразно.

2023-08-29 06:12 UTC, The7Fame approved these changes

2023-08-30 07:31 UTC, TsikhanauDzmitry approved these changes

2023-08-30 08:33 UTC, merged