Customize .rubocop.yml
Iorhael/trainee-planner pull request #16
Opened 2023-08-15 10:58 UTC by Iorhael

## Task: 
Customize .rubocop.yml
## Change proposed in this pull request:
Enable NewCops and disable SuggestExtensions in `.rubocop.yml`

2023-08-15 15:10 UTC, The7Fame approved these changes

2023-08-16 10:52 UTC, TsikhanauDzmitry requested changes

2023-08-16 10:52 UTC, TsikhanauDzmitry commented on .rubocop.yml
> +  SuggestExtensions: false
Зачем это было добавлено?

2023-08-16 11:53 UTC, Iorhael commented on .rubocop.yml
> +  SuggestExtensions: false
C целью устранения сообщений `The following cops were added to RuboCop, but are not configured...` и
`The following RuboCop extension libraries are installed but not loaded in config...` при генерации кода при помощи команды `rails generate`, а также `bundle exec rubocop`

2023-08-16 12:06 UTC, The7Fame approved these changes

2023-08-18 07:55 UTC, TsikhanauDzmitry approved these changes

2023-08-18 08:02 UTC, merged