User controllers and views
Iorhael/trainee-planner pull request #17
Opened 2023-08-15 15:19 UTC by Iorhael

2023-09-13 13:43 UTC, The7Fame commented on app/views/layouts/_loggedin.html.erb
может лучше его назвать user_dropdown?

2023-09-13 13:43 UTC, The7Fame commented on app/views/layouts/_registration.html.erb
> +</div>
Лишний пробел, если не ошибаюсь.

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/confirmations/new.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/mailer/confirmation_instructions.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/mailer/email_changed.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/mailer/password_change.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/mailer/reset_password_instructions.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/mailer/unlock_instructions.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/passwords/edit.html.erb
Есть перевод?

2023-09-13 13:43 UTC, The7Fame commented on app/views/users/passwords/new.html.erb
Есть перевод?

2023-09-13 18:35 UTC, Iorhael commented on app/views/layouts/_loggedin.html.erb
Согласен, исправлено.

2023-09-13 18:42 UTC, Iorhael commented on app/views/users/confirmations/new.html.erb
Исправил) Теперь есть.

2023-09-13 18:58 UTC, Iorhael commented on app/views/users/mailer/confirmation_instructions.html.erb
Исправлено.

2023-09-13 19:01 UTC, Iorhael commented on app/views/users/mailer/email_changed.html.erb
Готово.

2023-09-13 19:05 UTC, Iorhael commented on app/views/users/mailer/password_change.html.erb
Готово.

2023-09-13 19:10 UTC, Iorhael commented on app/views/users/mailer/reset_password_instructions.html.erb
Исправлено.

2023-09-13 19:13 UTC, Iorhael commented on app/views/users/mailer/unlock_instructions.html.erb
Исправлено.

2023-09-13 19:50 UTC, Iorhael commented on app/views/users/passwords/edit.html.erb
Добавлено.

2023-09-13 19:50 UTC, Iorhael commented on app/views/users/passwords/new.html.erb
Добавлено.

2023-09-14 10:02 UTC, The7Fame approved these changes

2023-09-15 08:19 UTC, TsikhanauDzmitry requested changes

2023-09-15 08:19 UTC, TsikhanauDzmitry commented on app/views/users/unlocks/new.html.erb
Тут все только на английском?

2023-09-15 08:19 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
Странное поведение. Я думал, что эта страница будет всем показываться в любом случае

2023-09-15 08:19 UTC, TsikhanauDzmitry commented on spec/routings/user_routing_spec.rb
> +  end
Тут больше вопрос к роутам, но с тестами оно видно лучше. Давай уберем `users` из путей?

2023-09-15 12:55 UTC, Iorhael commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
Да

2023-09-15 12:57 UTC, Iorhael commented on spec/controllers/home_controller_spec.rb
Я решил, что т.к. на главной странице должна отображаться персональная информация (такая как кол-во ивентов для конкретного юзера), то решил, что предварительно нужно аутентифицироваться.

2023-09-15 13:08 UTC, Iorhael commented on app/views/users/unlocks/new.html.erb
Верно, не заметил. Исправлено.

2023-09-15 14:13 UTC, The7Fame approved these changes

2023-09-18 11:28 UTC, Iorhael commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
Исправлено.

2023-09-18 15:46 UTC, The7Fame commented on app/assets/stylesheets/components/notifications.scss
> +}
Пустая строчка

2023-09-18 15:46 UTC, The7Fame commented on app/assets/stylesheets/components/fields.scss
> +}
Пустая строчка

2023-09-18 15:46 UTC, The7Fame commented on app/assets/stylesheets/components/buttons.scss
> +}
Пустая строчка

2023-09-18 15:46 UTC, The7Fame commented on app/assets/stylesheets/user.scss
> +}
Пустая строчка

2023-09-18 16:18 UTC, The7Fame submitted a review, later dismissed

2023-09-19 06:49 UTC, Iorhael commented on spec/controllers/home_controller_spec.rb
> +    end
Исправлено.

2023-09-19 09:09 UTC, The7Fame approved these changes

2023-09-20 09:23 UTC, TsikhanauDzmitry approved these changes

2023-09-20 09:43 UTC, merged