Add category model
Iorhael/trainee-planner pull request #20
Opened 2023-08-24 21:03 UTC by Iorhael

## Task: 
Add category model
## Changes proposed in this pull request:
* Add category model and migration
* Write seeds for category
* Write spec for category model

2023-08-25 06:56 UTC, The7Fame approved these changes

2023-08-25 09:41 UTC, TsikhanauDzmitry requested changes

2023-08-25 09:41 UTC, TsikhanauDzmitry commented on spec/factories/categories.rb
> +  end
Смотри, если у тебя всего 3 категории, то есть несколько путей решения проблемы:
1. Сделать 3 разных фактори, где каждая отвечает за одно состояние
2. Сделать рандомную выборку из категорий, а потом добавить трейты

2023-08-25 14:13 UTC, Iorhael commented on spec/factories/categories.rb
> +  end
Если я правильно понял, то готово)

2023-08-28 04:47 UTC, The7Fame approved these changes

2023-08-28 08:54 UTC, TsikhanauDzmitry approved these changes

2023-08-28 09:06 UTC, merged