Main page
Iorhael/trainee-planner pull request #22
Opened 2023-08-30 15:27 UTC by Iorhael

2023-09-06 06:47 UTC, The7Fame commented on app/views/layouts/_locales.erb
> +    <li><%= link_to t("nav.en"), { locale: :en }, class: "dropdown-item"%></li>
Лучше разделить пробелом `class: "dropdown-item"%>`. Как думаешь?

2023-09-06 08:51 UTC, Iorhael commented on app/views/layouts/_locales.erb
> +    <li><%= link_to t("nav.en"), { locale: :en }, class: "dropdown-item"%></li>
Да, согласен. Готово.

2023-09-06 09:04 UTC, The7Fame submitted a review, later dismissed

2023-09-06 13:42 UTC, The7Fame approved these changes

2023-09-07 12:54 UTC, TsikhanauDzmitry requested changes

2023-09-07 12:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +
Это можно не отделять пустыми строчками

2023-09-07 12:54 UTC, TsikhanauDzmitry commented on app/views/layouts/application.html.erb
> -    <p class="alert"><%= alert %></p>
А почему вывод уведомлений был удален?

2023-09-07 12:54 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
> +    end
Давай для этого мы сделаем отдельный файл, где будут тестироваться только смены языков. Все-таки у тебя для этого даже логика немного другая

2023-09-08 06:43 UTC, Iorhael commented on app/views/layouts/_header.html.erb
> +    <% end %>
Можно, поправил.

2023-09-08 06:43 UTC, Iorhael commented on app/views/layouts/_header.html.erb
> +
Исправил.

2023-09-08 06:45 UTC, Iorhael commented on app/views/layouts/application.html.erb
> -    <p class="alert"><%= alert %></p>
Думал добавить общий partial для уведомлений в отдельном PR, но решил, что можно и в этом. Исправил.

2023-09-08 07:34 UTC, Iorhael commented on spec/features/home_spec.rb
> +    end
Не уверен, что правильно реализовал, но исправил.

2023-09-08 08:10 UTC, The7Fame approved these changes

2023-09-08 11:39 UTC, TsikhanauDzmitry requested changes

2023-09-08 11:39 UTC, TsikhanauDzmitry commented on app/helpers/application_helper.rb
> +  end
Может лучше для этого отдельный хэлпер создать?

2023-09-08 11:39 UTC, TsikhanauDzmitry commented on app/helpers/application_helper.rb
> +    bootstrap_alert_class[level.to_sym]
Что будет, если передать несуществующий ключ?

2023-09-08 11:39 UTC, TsikhanauDzmitry commented on app/helpers/application_helper.rb
> +    }
Не желательно такое хранить в методе. Это можно сделать константой и зафризить

2023-09-08 11:39 UTC, TsikhanauDzmitry commented on app/helpers/application_helper.rb
Вообще у меня есть предположение, что ты подсмотрел эту реализацию у Даши...

2023-09-08 13:10 UTC, Iorhael commented on app/helpers/application_helper.rb
Не совсем) У меня довольно давно есть эта реализация, там правда драфтовый PR, который скорее всего закрою, т.к. не будет необходимости выносить это в отдельный PR. Ссылка на коммит с изменениями: https://github.com/Iorhael/trainee-planner/pull/24/commits/43f97adcba392f40b9c23c64cc1ec1805dd3671c

2023-09-08 13:25 UTC, Iorhael commented on app/helpers/application_helper.rb
> +  end
Согласен, есть.

2023-09-08 13:31 UTC, Iorhael commented on app/helpers/application_helper.rb
> +    }
Исправил.

2023-09-11 05:41 UTC, The7Fame approved these changes

2023-09-11 14:26 UTC, TsikhanauDzmitry requested changes

2023-09-11 14:26 UTC, TsikhanauDzmitry commented on app/helpers/bootstrap_helper.rb
> +module BootstrapHelper
Давай лучше дадим имя, которое связано с флеш-сообщениями

2023-09-11 14:36 UTC, The7Fame approved these changes

2023-09-12 06:16 UTC, TsikhanauDzmitry approved these changes

2023-09-12 07:58 UTC, merged