Fix bootstrap
Iorhael/trainee-planner pull request #28
Opened 2023-09-04 12:47 UTC by Iorhael

## Task: 
Fix bootstrap to allow on-the-fly style compilation
## Changes proposed in this pull request:
* Remove `cssbundling-rails` and `jsbundling-rails` gems
* Add `bootstrap` gem
* Add necessary configuration

2023-09-05 06:42 UTC, The7Fame submitted a review, later dismissed

2023-09-05 07:57 UTC, TsikhanauDzmitry requested changes

2023-09-05 07:57 UTC, TsikhanauDzmitry commented on config/environments/development.rb
> +  config.serve_static_assets = true
Зачем это было добавлено?

2023-09-05 08:21 UTC, Iorhael commented on config/environments/development.rb
> +  config.serve_static_assets = true
Я думал, что без этой настройки asset-ы не будут компилироваться на лету, но оказалось, что всё работает и без этого. Спасибо, убрал.

2023-09-05 09:01 UTC, The7Fame approved these changes

2023-09-06 09:32 UTC, TsikhanauDzmitry approved these changes

2023-09-06 10:31 UTC, merged