Add category controller and views
Iorhael/trainee-planner pull request #30
Opened 2023-09-15 19:17 UTC by Iorhael

## Task: 
Add category view and controller
## Changes proposed in this pull request:
* Add controller for category
* Add  and localize views for category
* Update navigation bar
### Views:
*index page

2023-09-20 09:11 UTC, The7Fame commented on .rubocop.yml
> +    - app/controllers/**/*
Это для чего?

2023-09-20 09:11 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +end
Метода show нет?

2023-09-20 09:50 UTC, Iorhael commented on .rubocop.yml
> +    - app/controllers/**/*
Т.к. я убрал методы `create` и `update` из `RegistrationController` за отстутствием необходимости их кастомизации, то rubocop стал ругаться на то, что в этом же контроллере в before_action упомянуты эти методы. Это относятся к #17. Поребейзил ветку, теперь здесь не будет этих изменений.

2023-09-20 13:48 UTC, The7Fame submitted a review, later dismissed

2023-09-20 14:40 UTC, TsikhanauDzmitry requested changes

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +  end
Классический момент, что никто не делает проверок на этот метод. А если оно не удалится? Такое случается, когда какие-то проблемы с БД и валидностью моделей.

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/_category.html.erb
> +    { bs_toggle: :modal, bs_target: "##{dom_id(category)}" }%>
Очень страшно выглядит. Не находишь? Думаю, что лучше будет так:

```
    <%= button_tag t('.edit'), 
                   class: "btn btn-primary", 
                   data: { bs_toggle: :modal, bs_target: "##{dom_id(category)}" }%>
```

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/_category.html.erb
> +  method: :delete %></td>
Очень страшно выглядит. Не находишь? Думаю, что лучше будет так:
```
  <td>
    <%= button_to t('.delete'),
                  category_path(category, locale: I18n.locale),
                  class: 'btn btn-danger',
                  data: { confirm: t('.are_you_sure'), turbo_confirm: t('.are_you_sure') },
                  method: :delete %>
  </td>
```

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/_no_categories.html.erb
> +  { target_id: 'new-category-modal', modal_type: 'create', category: Category.new } %>
У тебя какие-то проблемы с переносами. Не находишь?)

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/index.html.erb
> +      { target_id: 'new-category-modal', modal_type: 'create', category: Category.new } %>
У тебя какие-то проблемы с переносами. Не находишь?)

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/index.html.erb
> +          <th scope="col"></th>
Круто, а зачем?

2023-09-20 14:40 UTC, TsikhanauDzmitry commented on app/views/categories/index.html.erb
> +          { target_id: "#{dom_id(category)}", modal_type: 'edit', category: category } %>
У тебя какие-то проблемы с переносами. Не находишь?)

2023-09-20 20:08 UTC, Iorhael commented on app/views/categories/index.html.erb
> +          <th scope="col"></th>
Колонки для `edit` и `delete`)

2023-09-22 14:30 UTC, The7Fame submitted a review, later dismissed

2023-09-25 07:57 UTC, TsikhanauDzmitry requested changes

2023-09-25 07:57 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @category = Category.new(category_params)
Не думаю, что так правильно делать. Мы же создаем пользователю категорию

2023-09-25 13:44 UTC, Iorhael commented on app/controllers/categories_controller.rb
> +    @category = Category.new(category_params)
Исправлено.

2023-09-26 05:56 UTC, The7Fame commented on spec/views/categories/_form_modal.html.erb_spec.rb
Может разбить файл на два? (один для `create`, другой для `edit`)

2023-09-26 06:05 UTC, Iorhael commented on spec/views/categories/_form_modal.html.erb_spec.rb
Готово.

2023-09-26 19:08 UTC, The7Fame approved these changes

2023-09-28 06:05 UTC, TsikhanauDzmitry approved these changes

2023-09-28 19:22 UTC, merged