Add event controller and views
Iorhael/trainee-planner pull request #31
Opened 2023-09-15 19:25 UTC by Iorhael

## Task: 
Add event views and controller
## Changes proposed in this pull request:
* Add controller for event
* Add  and localize views for event
* Update navigation bar
### Views:
* index page (en):
![image](https://github.com/Iorhael/trainee-planner/assets/132287268/68b338d8-7fff-430b-b69c-f255b2043539)
* edit page (ru):
![image](https://github.com/Iorhael/trainee-planner/assets/132287268/b64cddd2-0aa5-412f-b568-c6ee40ad5c22)
* create page (en):
![image](https://github.com/Iorhael/trainee-planner/assets/132287268/8c69bae1-5abc-46c8-899f-c0134f6474fa)

2023-09-21 05:44 UTC, The7Fame commented on app/controllers/events_controller.rb
> +  end
Может лучше вынести в scope ` .order(:id)` и сделать его дефолтным?

2023-09-21 05:44 UTC, The7Fame commented on app/views/events/index.html.erb
> +      <thead>
Таблицу лучше вынести в отдельный паршал.

2023-09-25 09:03 UTC, Iorhael commented on app/views/events/index.html.erb
> +      <thead>
Готово.

2023-09-26 05:56 UTC, The7Fame commented on app/controllers/events_controller.rb
> +    if @event.save
Событие просто создаётся или привязывается к пользователю?

2023-09-26 05:56 UTC, The7Fame commented on spec/views/events/_form_modal.html.erb_spec.rb
Может разбить файл на два? (один для create, другой для edit)

2023-09-26 06:09 UTC, Iorhael commented on spec/views/events/_form_modal.html.erb_spec.rb
Готово.

2023-09-26 14:16 UTC, Iorhael commented on app/controllers/events_controller.rb
> +    if @event.save
Исправлено.

2023-09-26 19:17 UTC, The7Fame approved these changes

2023-09-28 06:14 UTC, TsikhanauDzmitry requested changes

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on .rubocop.yml
> +    - spec/**/*
Зачем это было добавлено?

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on app/javascript/application.js
Зачем это все было добавлено?

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on app/views/events/_table.html.erb
> +      <th scope="col"><%= Event.human_attribute_name(:reminder_time) %></th>
А разве так правильно? Лучше все во вьюхах делать через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on app/views/events/index.html.erb
> +      <p class="fs-1"><%= Event.model_name.human(count: 2) %></p>
А разве так правильно? Лучше все во вьюхах делать через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +          <%= link_to Event.model_name.human(count: 2), events_path, class: 'nav-link' %>
А разве так правильно? Лучше все во вьюхах делать через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
А что это и для чего?

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on spec/views/events/index.html.erb_spec.rb
> +  it { expect(rendered).to have_content('Event time') }
Это все должно быть через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on spec/views/events/_no_categories.html.erb_spec.rb
> +  it { expect(rendered).to have_button('Create first event') }
Это все должно быть через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on spec/views/events/_form_modal_edit_spec.rb
> +    it { expect(rendered).to have_button('Close') }
Это все должно быть через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on spec/views/events/_form_modal_create_spec.rb
> +    it { expect(rendered).to have_button('Close') }
Это все должно быть через `I18`

2023-09-28 06:14 UTC, TsikhanauDzmitry commented on spec/features/events/index.html.erb_spec.rb
> +    it { expect(page).to have_button('Close') }
Это все должно быть через `I18`

2023-09-29 11:50 UTC, Iorhael commented on .rubocop.yml
> +    - spec/**/*
В [spec/controllers/events/events_controller_update_spec.rb](https://github.com/Iorhael/trainee-planner/pull/31/files#diff-fce3c3525f2cc38da4d0a03fa555a11257c51c40c213ac6391fb2f4ffb737a85) для проверки корректности работы `putch` метода `EventsController` я создавал второго пользователя и его категорию. Rubocop ругается на слишком большое кол-во переменным (6/5), но я не вижу способа уменьшить кол-во переменных в данном контексте.

2023-09-29 14:48 UTC, Iorhael commented on spec/views/events/_form_modal_create_spec.rb
> +    it { expect(rendered).to have_button('Close') }
Исправлено.

2023-09-29 14:48 UTC, Iorhael commented on spec/views/events/_form_modal_edit_spec.rb
> +    it { expect(rendered).to have_button('Close') }
Исправлено.

2023-09-29 14:48 UTC, Iorhael commented on spec/views/events/_no_categories.html.erb_spec.rb
> +  it { expect(rendered).to have_button('Create first event') }
Исправлено.

2023-09-29 14:48 UTC, Iorhael commented on spec/views/events/index.html.erb_spec.rb
> +  it { expect(rendered).to have_content('Event time') }
Исправлено.

2023-10-02 05:52 UTC, Iorhael commented on .rubocop.yml
> +    - spec/**/*
Вместо отключения копа увеличил кол-во допустимых хелперов.

2023-10-02 07:58 UTC, The7Fame approved these changes

2023-10-02 08:05 UTC, TsikhanauDzmitry approved these changes

2023-10-02 08:07 UTC, merged