Update relations between models
Iorhael/trainee-planner pull request #32
Opened 2023-09-18 11:42 UTC by Iorhael

## Task:
Update user-categories relations
## Change proposed in this pull request:
* Update relations between user, category and event
* Update seeds
* Update model tests

2023-09-18 15:46 UTC, The7Fame approved these changes

2023-09-18 18:14 UTC, TsikhanauDzmitry requested changes

2023-09-18 18:14 UTC, TsikhanauDzmitry commented on app/models/event.rb
> -  belongs_to :user
Почему это было удалено?

2023-09-18 18:14 UTC, TsikhanauDzmitry commented on db/migrate/20230823150307_create_categories.rb
Это максимально не правильное решение. Если уже и делаешь какие-то изменения с БД, которые уже были задеплоены, то делай новую миграцию. Да, это не красиво, но зато правильно

2023-09-18 18:14 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +end.flatten
Что делает `flatten`?

2023-09-18 18:14 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +users_categories.each do |user_category|
Их всего же 3 теперь стало?

2023-09-19 06:55 UTC, Iorhael commented on app/models/event.rb
> -  belongs_to :user
Т.к. теперь связь между `user` и `event` осуществляется через "вложенную" для user ассоциацию `has_many` у модели `category`.

2023-09-19 07:05 UTC, Iorhael commented on db/seeds/development.rb
> +end.flatten
Превращает двухмерный массив записей категорий для пользователей в одномерный для упрощения дальнейших манипуляций с данными.

2023-09-19 07:06 UTC, Iorhael commented on db/seeds/development.rb
> +users_categories.each do |user_category|
Верно. Исправил, теперь 30, по 10 на каждую категорию. Заодно можно сразу проверять работу пагинации.

2023-09-19 08:03 UTC, Iorhael commented on db/migrate/20230823150307_create_categories.rb
Согласен, грубая ошибка. Исправлено.

2023-09-19 09:08 UTC, The7Fame approved these changes

2023-09-20 09:25 UTC, TsikhanauDzmitry approved these changes

2023-09-20 09:45 UTC, merged