Add info about events count on home page
Iorhael/trainee-planner pull request #33
Opened 2023-09-20 21:15 UTC by Iorhael

2023-09-21 05:44 UTC, The7Fame commented on app/controllers/home_controller.rb
> +  end
Лучше назвать EventCounterService и хранить всё в модуле Services.
И лучше переписать `@counter = EventsCounter.new(current_user) if current_user.`

2023-09-22 06:35 UTC, Iorhael commented on app/controllers/home_controller.rb
> +  end
Хорошо, спасибо. Сделано.

2023-09-22 13:16 UTC, The7Fame submitted a review, later dismissed

2023-09-25 07:53 UTC, TsikhanauDzmitry requested changes

2023-09-25 07:53 UTC, TsikhanauDzmitry commented on app/services/user_services/events_counter.rb
> +    def initialize(user)
Если же мы реализу сервисы, то очень желательно прописывать четкие параметры для инициализации:
```
Это для метода инициализации:
def initialize(user:)

Это для вызова сервиса:
UserServices::EventsCounter.new(user: current_user)
```
Так в будующем разработчики будут понимать, что и куда вы передаете

2023-09-25 07:53 UTC, TsikhanauDzmitry commented on app/services/user_services/events_counter.rb
Вообще очень интересное решение, которое в принципе может существовать.

2023-09-26 05:47 UTC, The7Fame submitted a review, later dismissed

2023-09-28 06:16 UTC, TsikhanauDzmitry submitted a review, later dismissed

2023-10-03 05:34 UTC, The7Fame approved these changes

2023-10-04 07:58 UTC, TsikhanauDzmitry approved these changes

2023-10-04 08:01 UTC, merged