Events search
Iorhael/trainee-planner pull request #35
Opened 2023-09-27 15:13 UTC by Iorhael

2023-10-02 08:06 UTC, The7Fame commented on app/queries/events/search_query.rb
> +      new(*, **).call
Думаю, лучше написать args*, kwagrs**, чем просто звездочки, как думаешь ?

2023-10-02 08:06 UTC, The7Fame commented on app/queries/events/search_query.rb
> +      @search_params = search_params
Зачем здесь default'ое значение к `relation`, если потом передаются события пользователя?

2023-10-02 08:06 UTC, The7Fame commented on app/views/events/_search.html.erb
> +  <div class="row mb-4">
Пробелы `do  |f|%>`

2023-10-02 08:06 UTC, The7Fame commented on app/views/events/_search.html.erb
> +    </div>
Пробел нужен `<%=f`

2023-10-02 08:06 UTC, The7Fame commented on app/views/events/_search.html.erb
> +      </div>
Пробел `info"%>`

2023-10-02 10:56 UTC, Iorhael commented on app/queries/events/search_query.rb
> +      new(*, **).call
Мне, если честно, тоже привычнее *args, **kwargs, но rubocop ругается:

2023-10-02 11:05 UTC, Iorhael commented on app/queries/events/search_query.rb
> +      @search_params = search_params
Хм, я оставил дефолтное значение, т.к. думал, что в дальнейшем будет проще использовать этот объект, но в принципе да, сейчас это не нужно. Убрал.

2023-10-02 11:06 UTC, Iorhael commented on app/views/events/_search.html.erb
> +  <div class="row mb-4">
Исправил.

2023-10-02 11:06 UTC, Iorhael commented on app/views/events/_search.html.erb
> +      </div>
Исправил.

2023-10-02 11:06 UTC, Iorhael commented on app/views/events/_search.html.erb
> +    </div>
Исправил.

2023-10-03 05:34 UTC, The7Fame submitted a review, later dismissed

2023-10-03 07:33 UTC, TsikhanauDzmitry requested changes

2023-10-03 07:33 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +  end
1. А обязательно ли для этого метод делать? У тебя в любом случае будут ивенты
2. Это и в одну строчку поместится

2023-10-03 07:33 UTC, TsikhanauDzmitry commented on app/queries/events/search_query.rb
> +    end
Думаю, что это может быть в приватных методах

2023-10-03 07:33 UTC, TsikhanauDzmitry commented on app/queries/events/search_query.rb
> +    attr_reader :relation, :search_params
Это тоже можно в приват закинуть

2023-10-03 07:33 UTC, TsikhanauDzmitry commented on app/views/events/_search.html.erb
> +                              :name,
Зачем тут два раза `:name`?

2023-10-03 07:33 UTC, TsikhanauDzmitry commented on app/queries/events/search_query.rb
> +    def initialize(search_params, relation:)
Почему не def `initialize(search_params:, relation:)`?

2023-10-03 09:22 UTC, Iorhael commented on app/controllers/events_controller.rb
> +  end
Хм, и в правду. Исправлено.

2023-10-03 09:23 UTC, Iorhael commented on app/queries/events/search_query.rb
> +    end
Исправлено.

2023-10-03 09:23 UTC, Iorhael commented on app/queries/events/search_query.rb
> +    attr_reader :relation, :search_params
Исправлено.

2023-10-03 09:25 UTC, Iorhael commented on app/queries/events/search_query.rb
> +    def initialize(search_params, relation:)
Исправлено.

2023-10-03 10:13 UTC, Iorhael commented on app/views/events/_search.html.erb
> +                              :name,
Первый `:name` - это value_method (т.к. мы ищем по имени категории, а не по `id`), а второй - `text_method`:
[collection_select(method, collection, value_method, text_method, options = {}, html_options = {})](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-collection_select)

2023-10-04 07:30 UTC, The7Fame approved these changes

2023-10-04 08:05 UTC, TsikhanauDzmitry requested changes

2023-10-04 08:05 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +  end
А давай сделаем вообще сервис по поиску и фильтрации? Так мы сможем вообще любым модели искать и фильтровать. Просто мы должны сохранять приницп "тонких контроллеров"

2023-10-04 08:05 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +  end
У тебя уже есть `SearchQuery`. Сервис просто по определенным параметрам будет запускать ту или иную SearchQuery, которые ты потом будешь создавать

2023-10-04 08:05 UTC, TsikhanauDzmitry commented on app/queries/events/search_query.rb
> +    end
Так лучше не делать и оставить только `initialize` и `call` методы в паблике

2023-10-04 08:05 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +      Events::SearchQuery.call(search_params:, relation: current_user.events)
Рекомендую от этого отказаться и сделать более явный вид: `Events::SearchQuery.new(search_params:, relation: current_user.events).call`

2023-10-04 09:50 UTC, Iorhael commented on app/controllers/events_controller.rb
> +      Events::SearchQuery.call(search_params:, relation: current_user.events)
Исправлено.

2023-10-04 09:50 UTC, Iorhael commented on app/queries/events/search_query.rb
> +    end
Исправлено.

2023-10-04 09:50 UTC, Iorhael commented on app/controllers/events_controller.rb
> +  end
Добавил.

2023-10-05 07:24 UTC, The7Fame commented on app/controllers/events_controller.rb
> +
Может эту логику в сервис добавить?

2023-10-05 13:32 UTC, Iorhael commented on app/controllers/events_controller.rb
> +
Окей, сделано.

2023-10-05 13:45 UTC, The7Fame approved these changes

2023-10-06 07:43 UTC, TsikhanauDzmitry approved these changes

2023-10-06 08:03 UTC, merged