Add WeatherService
Iorhael/trainee-planner pull request #38
Opened 2023-10-06 16:44 UTC by Iorhael

2023-10-11 07:58 UTC, Iorhael commented on app/decorators/weather/response_decorator.rb
> +    end
Готово.

2023-10-11 07:58 UTC, Iorhael commented on app/services/weather/data_fetcher.rb
> +      @event_time = event_time
Готово.

2023-10-11 07:58 UTC, Iorhael commented on app/services/weather/data_handler.rb
> +      @event_time = event_time
Готово.

2023-10-12 14:52 UTC, Iorhael commented on Gemfile
Есть.

2023-10-16 07:40 UTC, TsikhanauDzmitry requested changes

2023-10-16 07:40 UTC, TsikhanauDzmitry commented on app/views/events/show.html.erb
> +            <%= render partial: 'weather_widget' %>
Мне кажется, что тут отсутп лишний

2023-10-16 07:40 UTC, TsikhanauDzmitry commented on app/views/events/show.html.erb
> +            <% image_file = Dir.children('app/assets/images/landscapes').sample %>
Странная штука. Может лучше хэлпер какой-нибудь прикрутить?

2023-10-16 07:40 UTC, TsikhanauDzmitry commented on spec/views/events/show.html.erb_spec.rb
> +end
Почему это тут?

2023-10-16 09:41 UTC, Iorhael commented on spec/views/events/show.html.erb_spec.rb
> +end
Испрвлено, созданы отдельные директории для `share_examples` и `shared_context`.

2023-10-16 10:44 UTC, Iorhael commented on app/views/events/show.html.erb
> +            <% image_file = Dir.children('app/assets/images/landscapes').sample %>
Сделано.

2023-10-23 07:41 UTC, merged